version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitTestProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
- name: WmSalesforceProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v10.7.0
- name: WmGainsightProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v10.7.0
- name: SIQACloudStreamsTests
  gitServerName: moaaTestServerName
  gitUrl: https://github.webmethods.io/mjan
  gitUsername: moaa
  gitBranch: main
- name: DesignerStepsInCloudEditorPackage
  gitServerName: moaa
  gitUrl: https://github.com/santhu736852
  gitUsername: moaaSoftwareAG
  gitBranch: main
- name: WmLinkedInProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: latest
services:
- serviceName: project.gittest.integrations:aaa
  packages:
  - name: GitTestProject
    version: "1.0"
