version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitTestProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
- name: WmSalesforceProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v10.7.0
- name: WmGainsightProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v10.7.0
services:
- serviceName: project.gittest.integrations:aaa
  packages:
  - name: GitTestProject
    version: "1.0"
